# Generated by Django 4.1.1 on 2022-09-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_type_tender_options_type_tender_nomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inn', models.IntegerField(null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='type_tender',
            name='nomer',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер'),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.company', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагент',
                'ordering': ['name'],
            },
        ),
    ]
