# Generated by Django 4.1.1 on 2022-09-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_company_alter_type_tender_nomer_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('inn', models.IntegerField(null=True, verbose_name='ИНН')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['name'], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3)),
                ('win', models.CharField(choices=[('Филиал', 'Филиал'), ('Дилер', 'Дилер'), ('Другой', 'Другой')], default='Филиал', max_length=6)),
                ('number_tender', models.IntegerField()),
                ('price1', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Начальная цена')),
                ('data1', models.DateTimeField(null=True, verbose_name='Дата начала')),
                ('data2', models.DateTimeField(null=True, verbose_name='Дата конца')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена контракта')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.city', verbose_name='Город')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.client', verbose_name='Заказчик')),
                ('dialer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.dealer', verbose_name='Защита за дилером')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.filial', verbose_name='Филиал')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.product', verbose_name='Продукт')),
                ('type_tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.type_tender', verbose_name='Тип тендера')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные таблицы тендеров',
                'ordering': ['data1'],
            },
        ),
    ]
