# Generated by Django 4.1.1 on 2022-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_client_filial_product_staffer_alter_dealer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab',
            old_name='dialer',
            new_name='dealer',
        ),
    ]
