# Generated by Django 4.1.1 on 2022-09-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_rename_dialer_tab_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='number_tender',
            field=models.CharField(max_length=50, verbose_name='Номер тендера'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='safe',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=3, verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='win',
            field=models.CharField(choices=[('Филиал', 'Филиал'), ('Дилер', 'Дилер'), ('Другой', 'Другой')], default='Филиал', max_length=6, verbose_name='Победитель'),
        ),
    ]
