# Generated by Django 4.1.1 on 2022-09-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0008_alter_tab_number_tender_alter_tab_safe_alter_tab_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
    ]
