# Generated by Django 4.1.1 on 2022-09-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0009_alter_client_inn_alter_company_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.dealer', verbose_name='Дилер'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена контракта'),
        ),
    ]
