# Generated by Django 4.1.1 on 2022-09-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0010_alter_tab_dealer_alter_tab_price2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена контракта'),
        ),
    ]
