# Generated by Django 4.1.1 on 2022-09-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_alter_tab_price2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab',
            old_name='safe',
            new_name='protection',
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.DateTimeField(null=True, verbose_name='Дата внесения')),
                ('data2', models.DateTimeField(null=True, verbose_name='Должен состояться до: ')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.city', verbose_name='Город')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.client', verbose_name='Заказчик')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.dealer', verbose_name='Дилер')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные таблицы тендеров',
                'ordering': ['data1'],
            },
        ),
    ]
