# Generated by Django 4.1.1 on 2022-09-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_rename_safe_tab_protection_protection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protection',
            options={'ordering': ['data1'], 'verbose_name': 'Данные защиты', 'verbose_name_plural': 'Данные таблицы защиты'},
        ),
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['data1'], 'verbose_name': 'Данные тендеров', 'verbose_name_plural': 'Данные таблицы тендеров'},
        ),
    ]
