# Generated by Django 4.1.1 on 2022-09-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_alter_protection_options_alter_tab_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(max_length=200, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.city', verbose_name='Город'),
        ),
    ]
