# Generated by Django 4.1.1 on 2022-09-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_alter_city_region_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.company', verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.dealer', verbose_name='Дилер'),
        ),
        migrations.AlterField(
            model_name='protection',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.dealer', verbose_name='Дилер'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='type_tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tender.type_tender', verbose_name='Тип тендера'),
        ),
    ]
