# Generated by Django 4.1.1 on 2022-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0015_alter_city_region_alter_dealer_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='my_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
